language: java
env:
  global:
    secure: QLAG67a0Mh6XbtFtmaVQHJcY79/uYEhk3Z44QRQSi0aO1QX413kYRswqJRbcQYFuWYVqAgmsVg9Yx3um0F30v30rh7wYywhwLuzpoUk1y1zRUkK3iBAMrCrdiDhwnHbh6Tlt1+Fip7gIYmAHORBgdeWziK1zOg3R0/YwBuYrZXDSO3X9eci3J1AMEUgnnybj2y+01sjaV0IIB2hEZkWokVGeFLAh1dW9UZLOUNtLHohVCz6i63ThcrAk4hzBXMhLiHEV3/p/3oWf/jNgyk04VG3zg+M6BkY8a3fj61dFNOZceivwzdcDpX7/jqamHcys+7LVmQKplmWnXBhLFsXZQhuoxy/GFzMcGLU1f474roPNyu1KHEl3IJoUF1gwc2SW3UszYAJi2YAVS/O5s9hj6hLWwI1vQoFAAdK8kpAxsqYpduWdPsN5188uetCgt/utn9hm9Hrkapu+n4v66cDryEOPMrqGcQEfUXWopulsjURYRLbksgzTw9nvm9tQLxpb9Uz93i+EayjhwUgjxcMWfytp2bMCtvfiGmQ8kwyayn4yzv2N9qlgvJHyicQCI2R5gAA3YyJNoURiWh7gHuBdhJKSUevd3A5W6ZWG6uW/rHf2HgDAQvFhsf7G9yEsRs/CMRuRYe4/3y3WyJqcZGHX5oioFTqT+R+BMUOWWACjPSs=

jdk:
  - oraclejdk8

before_cache:
  - rm -rf $HOME/.m2/repository
  - find $HOME/.gradle -type f -name *.lock -exec rm {} +

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'

after_success:
  - ./gradlew jacocoTestReport coveralls
